project_name: tart

before:
  hooks:
    - .ci/set-version.sh
    # FIXME: Use a single build command after fix https://github.com/nicklockwood/SwiftFormat/issues/1645
    # - swift build --arch arm64 --arch x86_64 --configuration release --product tart
    - swift build --arch arm64 --configuration release --product tart
    - swift build --arch x86_64 --configuration release --product tart
    - mkdir -p .build/universal
    - lipo -create -output .build/universal/tart .build/arm64-apple-macosx/release/tart .build/x86_64-apple-macosx/release/tart
    - gon gon.hcl

builds:
  - id: tart
    builder: prebuilt
    goamd64: [v1]
    goos:
      - darwin
    goarch:
      - arm64
    binary: tart.app/Contents/MacOS/tart
    prebuilt:
      path: .build/universal/tart

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}"
    files:
      - src: Resources/embedded.provisionprofile
        dst: tart.app/Contents
        strip_parent: true
      - src: Resources/Info.plist
        dst: tart.app/Contents
        strip_parent: true
      - src: Resources/AppIcon.png
        dst: tart.app/Contents/Resources
        strip_parent: true
      - LICENSE

release:
  prerelease: auto

brews:
  - name: tart
    repository:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    license: "Fair Source"
    description: Run macOS and Linux VMs on Apple Hardware
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
      generate_completions_from_executable(libexec/"tart.app/Contents/MacOS/tart", "--generate-completion-script")
    custom_block: |
      depends_on :macos => :ventura
